# Generated by Django 3.1 on 2020-08-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodrider.restaurant'),
        ),
        migrations.AddField(
            model_name='menuitemoption',
            name='menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodrider.menuitem'),
        ),
    ]
