# Generated by Django 3.1 on 2020-08-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0002_auto_20200825_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemoption',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrider.menuitemoption'),
        ),
    ]
