# Generated by Django 3.1 on 2020-08-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0005_auto_20200825_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='option',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodrider.menuitemoption'),
        ),
    ]
