# Generated by Django 3.1 on 2020-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0006_auto_20200825_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dish_type',
            field=models.CharField(choices=[('S', 'Starters'), ('M', 'Main Course'), ('D', 'Desserts')], default='M', max_length=1),
        ),
    ]
