# Generated by Django 3.1 on 2020-08-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0007_auto_20200825_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemoption',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodrider.menuitem'),
        ),
    ]
