# Generated by Django 3.1 on 2020-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0009_auto_20200825_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemoption',
            name='menu',
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
