# Generated by Django 3.1 on 2020-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0013_auto_20200825_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemoption',
            old_name='price',
            new_name='nominal_price',
        ),
        migrations.AddField(
            model_name='menuitemoption',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
