# Generated by Django 3.1 on 2020-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0015_auto_20200825_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemoption',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
    ]
