# Generated by Django 3.1 on 2020-08-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0018_shippingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default='39.00', max_digits=7),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'Placed'), ('CD', 'Confirmed'), ('CK', 'Cooking'), ('RY', 'Ready'), ('PU', 'Picked Up'), ('OW', 'On the way'), ('DV', 'Delivered')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='IswljJ4hyQcgbGxoyMmWAKDnG2m9AQ', editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrider.menuitemoption'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodrider.order'),
        ),
    ]
