# Generated by Django 3.1 on 2020-08-26 06:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0019_auto_20200826_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemoption',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('39'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='X7Qf1VKFTxF611jSsMSjkiSG6iz5hv', editable=False, max_length=30, null=True, unique=True),
        ),
    ]
