# Generated by Django 3.1 on 2020-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0020_auto_20200826_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='Ut6Vua1hhBhqXY30x92GhROPlIkQ5F', editable=False, max_length=15, null=True, unique=True),
        ),
    ]
