# Generated by Django 3.1 on 2020-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0021_auto_20200826_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='ZKmqmUWsukb4AqZ', editable=False, max_length=15, null=True, unique=True),
        ),
    ]
