# Generated by Django 3.1 on 2020-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0022_auto_20200826_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='uWlmzvg9WpaW2s2', max_length=15, null=True, unique=True),
        ),
    ]
