# Generated by Django 3.1 on 2020-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0024_auto_20200826_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Confirmed'), (3, 'Cooking'), (4, 'Ready'), (5, 'Picked Up'), (6, 'On the way'), (7, 'Delivered')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='7R5ZNtS94JDoMFH', max_length=15, null=True, unique=True),
        ),
    ]
