# Generated by Django 3.1 on 2020-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0026_auto_20200826_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='5I7JeGOqwavtLL0', max_length=15, null=True, unique=True),
        ),
    ]
