# Generated by Django 3.1 on 2020-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0029_auto_20200826_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='Mjo12brGyzgoPeU', max_length=15, null=True, unique=True),
        ),
    ]
