# Generated by Django 3.1 on 2020-08-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0034_auto_20200826_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingadress',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='shippingadress',
            name='state',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='ffM8VDTUv8v4Bf4', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrider.order'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
