# Generated by Django 3.1 on 2020-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0035_auto_20200827_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='Gkh1E1dJQYEpT0o', max_length=15, null=True, unique=True),
        ),
    ]
