# Generated by Django 3.1 on 2020-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0036_auto_20200827_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
