# Generated by Django 3.1 on 2020-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0037_auto_20200827_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
