# Generated by Django 3.1 on 2020-08-29 19:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0040_auto_20200829_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemoption',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='dish_type',
            field=models.CharField(choices=[('S', 'Starters'), ('M', 'Main Course'), ('D', 'Desserts')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='item_type',
            field=models.CharField(choices=[('VEG', 'Veg'), ('NVG', 'Non-Veg')], default='VEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='nominal_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
    ]
