# Generated by Django 3.1 on 2020-08-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0042_driverdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrider.driverdetail'),
        ),
    ]
