# Generated by Django 3.1 on 2020-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0043_auto_20200830_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rorder_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
