# Generated by Django 3.1 on 2020-09-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0044_order_rorder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrider.customer')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rorder_id',
            new_name='razor_order_id',
        ),
        migrations.DeleteModel(
            name='ShippingAdress',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodrider.shippingaddress'),
        ),
    ]
