# Generated by Django 3.1 on 2020-09-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0045_auto_20200901_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
