# Generated by Django 3.1 on 2020-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrider', '0046_auto_20200901_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
